//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoEntities2 : DbContext
    {
        public ProyectoEntities2()
            : base("name=ProyectoEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAB_CATEGORIAS> TAB_CATEGORIAS { get; set; }
        public virtual DbSet<TAB_ESTADO> TAB_ESTADO { get; set; }
        public virtual DbSet<TAB_IMAGENES> TAB_IMAGENES { get; set; }
        public virtual DbSet<TAB_INGREDIENTES> TAB_INGREDIENTES { get; set; }
        public virtual DbSet<TAB_INSTRUCCIONES> TAB_INSTRUCCIONES { get; set; }
        public virtual DbSet<TAB_RECETAS> TAB_RECETAS { get; set; }
        public virtual DbSet<TAB_TAGS> TAB_TAGS { get; set; }
    }
}
