//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgra.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAB_RECETAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TAB_RECETAS()
        {
            this.TAB_IMAGENES = new HashSet<TAB_IMAGENES>();
            this.TAB_INGREDIENTES = new HashSet<TAB_INGREDIENTES>();
            this.TAB_INSTRUCCIONES = new HashSet<TAB_INSTRUCCIONES>();
        }
    
        public int COD_RECETA { get; set; }
        public string NOM_RECETA { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public string DURACION { get; set; }
        public string PORCIONES { get; set; }
        public Nullable<int> ID_TAGS { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public string UserName { get; set; }
        public string FECHA_CREACION { get; set; }
        public string FECHA_MODIFICACION { get; set; }
    
        public virtual TAB_CATEGORIAS TAB_CATEGORIAS { get; set; }
        public virtual TAB_ESTADO TAB_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_IMAGENES> TAB_IMAGENES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_INGREDIENTES> TAB_INGREDIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAB_INSTRUCCIONES> TAB_INSTRUCCIONES { get; set; }
        public virtual TAB_TAGS TAB_TAGS { get; set; }
    }
}
